# This is a basic workflow to help you get started with Actions

name: CI-initial

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
    paths:
      - sockshop/initial/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  yandex-cloud:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # install terraform
    steps:

     - name: Check out code
       uses: actions/checkout@v3
       with:
         repository: suxarikisme/endgame
         ref: refs/heads/master

     - name: Install YC
       run: |
        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /opt/yÑ -n 

     - name: Install kubectl
       uses: azure/setup-kubectl@v2.0
       id: install

     - name: Run YC create
       env:
        YC_FILE: ${{ secrets.YC_KEY }}
       run: |
        echo "$YC_FILE" >> yckey.json
        /opt/yc/bin/yc config profile create default
        /opt/yc/bin/yc config set service-account-key yckey.json

        export CLUSTER_NAME=$(/opt/yc/bin/yc managed-kubernetes cluster list --format json | grep name | awk '{ print $2 }' | tr -dc '[0-9A-Za-z-]')

        if [ -z "$CLUSTER_NAME"  ]; then
        /opt/yc/bin/yc managed-kubernetes cluster create  --name default --network-name default \
            --zone ru-central1-a --subnet-name default \
            --public-ip --release-channel regular --version 1.21 --cluster-ipv4-range 10.112.0.0/16 \
            --service-ipv4-range 10.96.0.0/16 --service-account-name default-sa \
            --node-service-account-name default-sa \
            --daily-maintenance-window start=23:00,duration=10h &> /dev/null && \
        /opt/yc/bin/yc managed-kubernetes node-group create --name default \
            --cluster-name default --platform-id standard-v2 --version 1.21 \
            --cores 2 --core-fraction 100 --memory 8 --fixed-size 2 --disk-type network-hdd \
            --location zone=ru-central1-a \
            --network-interface=subnets=default,ipv4-address=nat &> /dev/null
        fi

        /opt/yc/bin/yc managed-kubernetes cluster get-credentials --external --name default
        kubectl get all -n kube-system
     